/** Statische content van groningenrp.store */
const GRPContent = {
  rulesMeta: {
    title: 'Algemene Plaatselijke',
    titleAccent: 'Verordening',
    subtitle:
      'Alle regels die gelden binnen Utrecht Roleplay. Lees deze goed door voordat je de server joint.',
    total: 38,
    articles: 6,
    heavy: 13,
  },

  ruleArticleIcons: {
    algemeen: 'book',
    roleplay: 'gavel',
    criminaliteit: 'mask',
    voertuig: 'car',
    overheid: 'landmark',
    communicatie: 'radio',
  },

  ruleArticles: [
    {
      id: 'algemeen',
      title: 'Algemene Regels',
      num: 1,
      code: 'A',
      rules: [
        { id: 'A1', text: 'Het is verplicht om een werkende microfoon te hebben en te gebruiken tijdens het spelen.', severity: 'licht' },
        { id: 'A2', text: 'Het gebruik van cheats, hacks, exploits of andere derde partij software die een oneerlijk voordeel biedt is ten strengste verboden.', severity: 'zwaar' },
        { id: 'A3', text: 'Het is niet toegestaan om bugs of glitches te misbruiken. Meld deze altijd bij het staffteam.', severity: 'zwaar' },
        { id: 'A4', text: 'Respecteer alle spelers en staffleden. Toxisch gedrag, pesten of discriminatie wordt niet getolereerd.', severity: 'zwaar' },
        { id: 'A5', text: 'Het is verboden om informatie buiten het spel (Discord, stream, etc.) te gebruiken in het spel (metagaming).', severity: 'zwaar' },
        { id: 'A6', text: 'Powergaming is niet toegestaan. Dit betekent dat je geen acties mag forceren op andere spelers zonder hen de kans te geven te reageren.', severity: 'licht' },
        { id: 'A7', text: 'Het is verplicht om Nederlands te spreken in-game.', severity: 'licht' },
        { id: 'A8', text: 'Alt accounts zijn niet toegestaan. Eén speler per account.', severity: 'zwaar' },
        { id: 'A9', text: 'AFK zijn op plekken waar dit andere spelers belemmert is niet toegestaan.', severity: 'licht' },
        { id: 'A10', text: 'Het staffteam heeft altijd het laatste woord. Beslissingen van staff zijn definitief.', severity: 'licht' },
      ],
    },
    {
      id: 'roleplay',
      title: 'Roleplay Regels',
      num: 2,
      code: 'RP',
      rules: [
        { id: 'RP1', text: 'Je dient te allen tijde in karakter (in character) te blijven tijdens roleplay situaties.', severity: 'licht' },
        { id: 'RP2', text: 'Random Deathmatch (RDM) is verboden. Je mag niet zomaar andere spelers aanvallen zonder geldige roleplay reden.', severity: 'zwaar' },
        { id: 'RP3', text: 'Vehicle Deathmatch (VDM) is verboden. Het opzettelijk aanrijden van spelers met een voertuig is niet toegestaan.', severity: 'zwaar' },
        { id: 'RP4', text: 'New Life Rule (NLR): Na het overlijden vergeet je alles wat er is gebeurd voor je dood. Je mag niet terugkeren naar de plek waar je bent overleden.', severity: 'licht' },
        { id: 'RP5', text: 'FailRP is niet toegestaan. Gedraag je realistisch en passend bij je karakter.', severity: 'licht' },
        { id: 'RP6', text: 'Combat logging (uitloggen tijdens een roleplay situatie) is verboden.', severity: 'zwaar' },
        { id: 'RP7', text: 'Het is niet toegestaan om een scenario af te breken zonder geldige reden.', severity: 'licht' },
        { id: 'RP8', text: 'Copbaiting (opzettelijk politie uitlokken zonder reden) is niet toegestaan.', severity: 'licht' },
      ],
    },
    {
      id: 'criminaliteit',
      title: 'Criminaliteit Regels',
      num: 3,
      code: 'C',
      rules: [
        { id: 'C1', text: 'Er mogen maximaal 6 personen deelnemen aan een criminele activiteit.', severity: 'licht' },
        { id: 'C2', text: 'Overvallen mogen alleen plaatsvinden wanneer er voldoende politie in dienst is.', severity: 'licht' },
        { id: 'C3', text: 'Het gijzelen van andere spelers moet altijd een roleplay reden hebben.', severity: 'zwaar' },
        { id: 'C4', text: 'Scammen van andere spelers is niet toegestaan.', severity: 'zwaar' },
        { id: 'C5', text: 'Het is niet toegestaan om illegale activiteiten uit te voeren in safezones.', severity: 'licht' },
        { id: 'C6', text: 'Rippen (stelen van drugs/wapens) is alleen toegestaan met goede roleplay.', severity: 'licht' },
      ],
    },
    {
      id: 'voertuig',
      title: 'Voertuig Regels',
      num: 4,
      code: 'V',
      rules: [
        { id: 'V1', text: 'Pitstops zijn niet toegestaan. Je mag niet opzettelijk andere voertuigen van de weg duwen.', severity: 'licht' },
        { id: 'V2', text: 'Het rijden door onbegaanbaar terrein met een niet-geschikt voertuig is niet toegestaan.', severity: 'licht' },
        { id: 'V3', text: 'Het opzettelijk rammen van voertuigen is alleen toegestaan door de politie in specifieke situaties.', severity: 'licht' },
        { id: 'V4', text: 'Vluchten naar een garage om je voertuig op te slaan tijdens een achtervolging is niet toegestaan.', severity: 'licht' },
        { id: 'V5', text: 'Het stelen van overheidsvoertuigen is alleen toegestaan met een geldige roleplay reden.', severity: 'licht' },
      ],
    },
    {
      id: 'overheid',
      title: 'Overheid Regels',
      num: 5,
      code: 'O',
      rules: [
        { id: 'O1', text: 'Overheidspersoneel dient zich professioneel te gedragen tijdens dienst.', severity: 'licht' },
        { id: 'O2', text: 'Het lekken van overheidsinformatie naar criminelen is niet toegestaan.', severity: 'zwaar' },
        { id: 'O3', text: 'Corruptie is alleen toegestaan met toestemming van de leiding van je dienst.', severity: 'zwaar' },
        { id: 'O4', text: 'Het is verplicht om de juiste procedures te volgen tijdens arrestaties en boetes.', severity: 'licht' },
        { id: 'O5', text: 'Overheidspersoneel mag geen criminele activiteiten uitvoeren tijdens dienst.', severity: 'zwaar' },
      ],
    },
    {
      id: 'communicatie',
      title: 'Communicatie Regels',
      num: 6,
      code: 'COM',
      rules: [
        { id: 'COM1', text: 'Het gebruik van de porto (radio) is alleen toegestaan voor de functie waarvoor het bedoeld is.', severity: 'licht' },
        { id: 'COM2', text: 'Het opnemen van gesprekken in-game is alleen toegestaan met een telefoon item.', severity: 'licht' },
        { id: 'COM3', text: 'Het is niet toegestaan om 112 (politie) te bellen zonder geldige reden.', severity: 'licht' },
        { id: 'COM4', text: 'Streamers dienen een delay van minimaal 3 minuten te gebruiken.', severity: 'licht' },
      ],
    },
  ],

  storeCategories: [
    { id: 'coins', label: 'Coins', count: 12 },
    { id: 'staff', label: 'Staff Rangen', count: 27 },
    { id: 'unban', label: 'Unban Aanschaffen', count: 3 },
    { id: 'org', label: 'Budget Organisaties', count: 4 },
    { id: 'extra', label: "Staff Extra's", count: 4 },
    { id: 'orgextra', label: "Organisatie Extra's", count: 1 },
  ],

  storeRecentPayments: [
    { user: 'levgerritsen', initial: 'L', color: '#a855f7', badge: '1' },
    { user: 'Jay05234', initial: 'J', color: '#3b82f6' },
    { user: 'JK0316', initial: 'j', color: '#22c55e' },
  ],

  ingameCategories: [
    { id: 'all', label: 'Alles' },
    { id: 'autos', label: 'Autos', count: 27 },
    { id: 'nieuw', label: 'Nieuwe Autos', count: 6 },
    { id: 'wapens', label: 'Wapens', count: 10 },
    { id: 'vip-features', label: 'VIP Features', count: 12 },
    { id: 'vip-ranks', label: 'VIP Ranks', count: 3 },
    { id: 'chip', label: 'Chip Tunes', count: 3 },
    { id: 'season', label: 'Season Pass', count: 3 },
    { id: 'loodsen', label: 'Loodsen', count: 5 },
    { id: 'organisaties', label: 'Organisaties', count: 18 },
  ],

  ingameItems: [
    { cat: 'autos', name: 'Benefactor X63 MNSRY', desc: 'Unieke, krachtige X-klasse. (SNELSTE UIT DE STAD)', coins: 51, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'autos', name: 'Ubermacht 8M', desc: 'Ubermacht 8M Uniek krachtig', coins: 42, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'autos', name: 'SR63 MNSRY', desc: 'Supersnelle, exclusieve stationwagen.', coins: 40, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'autos', name: 'Oros MNSRY', desc: 'Krachtige snelle en unieke SUV.', coins: 48, image: 'assets/urp-logo.png' },
    { cat: 'autos', name: 'Pegassi Toros Venatus', desc: 'High Performance SUV met top snelheid en grip.', coins: 35, image: 'assets/urp-logo.png' },
    { cat: 'autos', name: 'Obey SR6 Demon', desc: 'Duivelse variant met nog meer vermogen. 350+ KM/H', coins: 35, image: 'assets/urp-logo.png' },
    { cat: 'nieuw', name: 'V12 Ciber Trock', desc: 'SNEL, MAXIMAAL 3X VERKOCHT!', coins: 50, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'nieuw', name: 'Benefactor S63T', desc: 'Geoptimaliseerd en extreem snel 1000kmh+ BULLETPROOF!', coins: 49, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'nieuw', name: 'Grotti Puro', desc: 'NIEUWSTE VOERTUIG, BEPERKTE VOORRAAD', coins: 45, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'wapens', name: 'VIP Blackmarket Level 3', desc: '🔥 BESTE WAPENS!', coins: 30, image: 'https://i.postimg.cc/rsPgQmQD/image-2025-11-29-010343241.png' },
    { cat: 'wapens', name: 'VIP Blackmarket Level 2', desc: '📍 Exclusieve locatie op je GPS', coins: 24, image: 'https://i.postimg.cc/Wbyf79yN/image-2025-11-29-010301756.png' },
    { cat: 'wapens', name: 'VIP Blackmarket Level 1', desc: '📍 Exclusieve locatie op je GPS', coins: 12, image: 'https://i.postimg.cc/kgBPJ60g/image-2025-11-29-010127120.png' },
    { id: 'revivemij', cat: 'vip-features', name: '/Revivemij Command', desc: '✅ Sneller terug in actie!', coins: 20, image: 'https://i.postimg.cc/XNCWFCJh/image-2025-11-29-004702256.png' },
    { cat: 'vip-features', name: 'VIP Messages Bundle', desc: 'De ultieme manier om indruk te maken!', coins: 17, image: 'https://i.postimg.cc/qBDnQGQC/image-2026-01-28-012637179.png' },
    { cat: 'vip-features', name: 'Autoradio Systeem', desc: '⭐ Sla je favorieten op voor snelle toegang!', coins: 15, image: 'https://i.postimg.cc/MKDXtyp6/c774150d-5ceb-4312-8cf4-5f9f29b357f4.png' },
    { cat: 'vip-features', name: 'VIP Backpack (Permanent)', desc: '✅ Perfect voor criminelen', coins: 15, image: 'https://i.postimg.cc/MKh8d0PC/image-2025-11-29-011911094.png' },
    { cat: 'vip-features', name: 'VIP Kill Message', desc: '⚠️ Diamond VIP krijgt dit automatisch!', coins: 10, image: 'https://i.postimg.cc/t4jQxcN5/screenshot-38.png' },
    { cat: 'vip-features', name: 'VIP Join Message', desc: '✅ Kleurrijke notificatie', coins: 10, image: 'https://i.postimg.cc/xT7vjPzC/image-2026-01-28-012424082.png' },
    { cat: 'vip-features', name: 'Taakstraf Wegkopen', desc: 'Koop je taakstraf direct weg', coins: 8, image: 'https://i.postimg.cc/gJDKGxKj/6fe92d56-a8ae-4f2b-812a-8a826a953a62.png' },
    { cat: 'vip-ranks', name: 'Diamond VIP (Lifetime)', desc: '👑 ULTIMATE TIER!', coins: 85, featured: true, image: 'https://i.postimg.cc/JhCHRz0P/image-2025-11-24-024428521.png' },
    { cat: 'vip-ranks', name: 'Gold VIP (3 Maanden)', desc: 'Premium voordelen 3 maanden', coins: 45, image: 'https://i.postimg.cc/JhCHRz0P/image-2025-11-24-024428521.png' },
    { cat: 'vip-ranks', name: 'Silver VIP (1 Maand)', desc: 'Starter VIP pakket', coins: 20, image: 'https://i.postimg.cc/JhCHRz0P/image-2025-11-24-024428521.png' },
    { cat: 'chip', name: 'Chip Tune Level 3', desc: 'Top Snelheid 500+', coins: 45, image: 'assets/urp-logo.png' },
    { cat: 'chip', name: 'Chip Tune Level 2', desc: '⚡ Direct actief na aankoop!', coins: 15, image: 'assets/urp-logo.png' },
    { cat: 'chip', name: 'Chip Tune Level 1', desc: '⚠️ Ongepaste woorden worden geblokkeerd', coins: 10, image: 'assets/urp-logo.png' },
    { cat: 'season', name: 'Season Pass Premium', desc: 'Alle season rewards', coins: 55, featured: true, image: 'assets/urp-logo.png' },
    { cat: 'loodsen', name: 'Coke Loods', desc: 'Productie loods', coins: 35, image: 'assets/urp-logo.png' },
    { cat: 'organisaties', name: 'Gang Starter Pack', desc: 'Start je eigen gang', coins: 60, image: 'assets/urp-logo.png' },
  ],
};

window.__GRP_RULE_DEFAULTS__ = {
  rulesMeta: GRPContent.rulesMeta,
  ruleArticles: GRPContent.ruleArticles,
  ruleArticleIcons: GRPContent.ruleArticleIcons,
};
